import { chores, days } from '../data'
import type { Assignment, Roommate } from '../types'
import { Icon } from './Icon'

type Props = { roommates: Roommate[]; assignments: Assignment[]; weekLabel: string; dates: Date[]; editing: boolean; onNextWeek: () => void; onPreviousWeek: () => void; onEditToggle: () => void; onChoreChange: (roommateId: string, day: string, nextChore: string) => void; onComplete: (assignmentId: string) => void }

export function ScheduleTable({ roommates, assignments, weekLabel, dates, editing, onNextWeek, onPreviousWeek, onEditToggle, onChoreChange, onComplete }: Props) {
  return <section className="schedule-card"><div className="schedule-toolbar"><div className="week-navigation"><button className="week-arrow" onClick={onPreviousWeek} aria-label="Previous week">‹</button><button className="week-select" onClick={onNextWeek}><span className="calendar">▣</span><span><strong>{weekLabel}</strong><small>Monday to Saturday</small></span><span className="down">⌄</span></button><button className="week-arrow" onClick={onNextWeek} aria-label="Next week">›</button></div><span className="today-pill">Selected week</span><button className={`edit-button ${editing ? 'editing' : ''}`} onClick={onEditToggle}><Icon name="edit" />{editing ? 'Done editing' : 'Edit schedule'}</button></div><div className="table-wrap"><table><thead><tr><th className="roommate-heading">ROOMMATE</th>{days.map((day, index) => <th key={day}><span>{day.slice(0, 3).toUpperCase()}</span><b>{dates[index].getDate()}</b></th>)}</tr></thead><tbody>{roommates.map((person, personIndex) => <tr key={person.id}><td className="person-cell"><span className="avatar" style={{ background: person.colour }}>{person.initials}</span><strong>{person.name}</strong></td>{days.map((day, dayIndex) => { const saved = assignments.find((assignment) => assignment.roommate_id === person.id && assignment.day === day); const current = chores.findIndex((chore) => chore.label === saved?.chore); const chore = chores[current >= 0 ? current : (personIndex + dayIndex) % chores.length]; const next = chores[(chores.indexOf(chore) + 1) % chores.length]; return <td key={day}><button disabled={!editing} className={`chore-chip ${chore.colour} ${saved?.completed ? 'completed' : ''}`} onClick={() => onChoreChange(person.id, day, next.label)} title={editing ? 'Click to change chore' : 'Select Edit schedule first'}><span>{saved?.completed ? '✓' : chore.icon}</span>{chore.label}</button>{saved && <button className={`complete-button ${saved.completed ? 'is-complete' : ''}`} onClick={() => !saved.completed && onComplete(saved.id)} disabled={saved.completed}>{saved.completed ? 'Completed' : 'Mark done'}</button>}</td> })}</tr>)}</tbody></table></div><div className="card-footer"><p><span className="spark">✦</span> {editing ? 'Click a chore to switch it' : 'Mark completed work, or use Edit schedule to change chores'}</p><p>Sunday is a rest day <span>☀</span></p></div></section>
}
