import { useCallback, useEffect, useMemo, useState } from 'react'
import './App.css'; import './components.css'; import './integration.css'; import './feedback.css'
import { api, type CurrentUser, type HistoryEntry } from './api'
import type { Assignment, Roommate } from './types'
import { AddRoommateModal } from './components/AddRoommateModal'; import { FeedbackModal } from './components/FeedbackModal'; import { Icon } from './components/Icon'; import { LoginScreen } from './components/LoginScreen'; import { ScheduleTable } from './components/ScheduleTable'; import { Sidebar } from './components/Sidebar'
const mondayOf = (date: Date) => { const value = new Date(date); value.setDate(value.getDate() - (value.getDay() + 6) % 7); value.setHours(0, 0, 0, 0); return value }
const isoDate = (date: Date) => date.toISOString().slice(0, 10)
const formatWeek = (start: Date) => { const end = new Date(start); end.setDate(end.getDate() + 5); return `${start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}` }
function App() {
 const [token, setToken] = useState(() => localStorage.getItem('roomie-token') ?? ''); const [user, setUser] = useState<CurrentUser | null>(null); const [roommates, setRoommates] = useState<Roommate[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [history, setHistory] = useState<HistoryEntry[]>([]); const [weekStart, setWeekStart] = useState(() => mondayOf(new Date())); const [editing, setEditing] = useState(false); const [showModal, setShowModal] = useState(false); const [showFeedback, setShowFeedback] = useState(false); const [notice, setNotice] = useState(''); const [activeView, setActiveView] = useState<'board' | 'history'>('board'); const [loading, setLoading] = useState(false)
 const weekKey = isoDate(weekStart); const dates = useMemo(() => Array.from({ length: 6 }, (_, index) => { const value = new Date(weekStart); value.setDate(value.getDate() + index); return value }), [weekStart]); const visibleAssignments = assignments.filter((assignment) => assignment.week_start === weekKey); const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2200) }
 const loadData = useCallback(async (accessToken: string) => { setLoading(true); try { const [person, people, chores, completed] = await Promise.all([api.me(accessToken), api.roommates(accessToken), api.assignments(accessToken), api.history(accessToken)]); setUser(person); setRoommates(people); setAssignments(chores); setHistory(completed) } catch (cause) { const message = cause instanceof Error ? cause.message : 'Could not load your schedule'; if (message.includes('token')) { localStorage.removeItem('roomie-token'); setToken(''); setUser(null) } else notify(message) } finally { setLoading(false) } }, [])
 useEffect(() => { if (token) void loadData(token) }, [token, loadData]); const login = async (email: string, password: string) => { const session = await api.login(email, password); localStorage.setItem('roomie-token', session.access_token); setToken(session.access_token) }
 const addRoommate = async (name: string) => { try { const created = await api.createRoommate(token, { name, colour: '#8d87dc' }); setRoommates((current) => [...current, created]); setShowModal(false); notify(`${name} joined the schedule`) } catch (cause) { notify(cause instanceof Error ? cause.message : 'Could not add roommate') } }
 const changeChore = async (roommateId: string, day: string, chore: string) => { const existing = visibleAssignments.find((assignment) => assignment.roommate_id === roommateId && assignment.day === day); try { const saved = existing ? await api.updateAssignment(token, existing.id, { chore, completed: false }) : await api.createAssignment(token, { roommate_id: roommateId, day, chore, week_start: weekKey }); setAssignments((current) => existing ? current.map((assignment) => assignment.id === saved.id ? saved : assignment) : [...current, saved]); notify('Chore updated') } catch (cause) { notify(cause instanceof Error ? cause.message : 'Could not update chore') } }
 const completeChore = async (id: string) => { try { const saved = await api.updateAssignment(token, id, { completed: true }); setAssignments((current) => current.map((assignment) => assignment.id === saved.id ? saved : assignment)); setHistory(await api.history(token)); notify('Marked as completed') } catch (cause) { notify(cause instanceof Error ? cause.message : 'Could not complete chore') } }
 const moveWeek = (amount: number) => setWeekStart((current) => { const next = new Date(current); next.setDate(next.getDate() + amount * 7); return next }); const shareSchedule = async () => { try { await navigator.clipboard.writeText(`Maple House chore schedule: ${formatWeek(weekStart)}`); notify('Schedule link copied') } catch { notify('Schedule is ready to share') } }; const sendFeedback = async (message: string, type: 'feedback' | 'help') => { try { await api.feedback(token, message, type); notify(type === 'help' ? 'Help request sent' : 'Feedback sent') } catch (cause) { notify(cause instanceof Error ? cause.message : 'Could not send message') } }
 if (!token) return <LoginScreen onLogin={login} />
 return <main className="app-shell"><Sidebar roommateCount={roommates.length} user={user} activeView={activeView} onViewChange={setActiveView} onNotify={notify} onFeedback={() => setShowFeedback(true)} onLogout={() => { localStorage.removeItem('roomie-token'); setToken(''); setUser(null) }} /><section className="content"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">r</span> roomie</div><button className="share-button" onClick={shareSchedule}><Icon name="share" />Share schedule</button></header><div className="page-heading"><div><p className="eyebrow">MAPLE HOUSE</p><h1>{activeView === 'board' ? 'Chore schedule' : 'Chore history'}</h1><p className="subtitle">{activeView === 'board' ? 'Everyone pulls their weight. No reminders needed.' : 'Your household’s completed chore rotation.'}</p></div>{activeView === 'board' && <button className="add-button" onClick={() => setShowModal(true)}><Icon name="plus" />Add roommate</button>}</div>{loading ? <div className="loading-card">Loading your household schedule…</div> : activeView === 'board' ? <><ScheduleTable roommates={roommates} assignments={visibleAssignments} weekLabel={formatWeek(weekStart)} dates={dates} editing={editing} onPreviousWeek={() => moveWeek(-1)} onNextWeek={() => moveWeek(1)} onEditToggle={() => setEditing((value) => !value)} onChoreChange={changeChore} onComplete={completeChore} /><section className="up-next"><div><p className="eyebrow">COMING UP</p><h2>Next week, the rotation continues.</h2></div><div className="next-avatars">{roommates.slice(0, 4).map((person) => <span key={person.id} className="avatar overlap" style={{ background: person.colour }}>{person.initials}</span>)}<button onClick={() => moveWeek(1)}>View next week <Icon name="chevron" /></button></div></section></> : <section className="history-card"><span>✓</span><h2>{history.length ? `${history.length} completed chores` : 'All caught up'}</h2>{history.length ? <div className="history-list">{history.slice(0, 8).map((entry) => <p key={entry.id}><strong>{roommates.find((person) => person.id === entry.roommate_id)?.name ?? 'Roommate'}</strong> completed {entry.chore}<small>{new Date(entry.completed_at).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</small></p>)}</div> : <p>Once chores are marked complete, their history will appear here.</p>}<button className="edit-button" onClick={() => setActiveView('board')}>Back to chore board</button></section>}</section>{showModal && <AddRoommateModal onClose={() => setShowModal(false)} onAdd={addRoommate} />}{showFeedback && <FeedbackModal type="feedback" onClose={() => setShowFeedback(false)} onSend={sendFeedback} />}{notice && <div className="toast">✓ {notice}</div>}</main>
}
export default App
